version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: dashboard-financeiro-postgres
    environment:
      POSTGRES_DB: dashboard_financeiro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard-financeiro-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dashboard_financeiro
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8080
      OPENEXCHANGERATES_APP_ID: ${OPENEXCHANGERATES_APP_ID:-sua_chave_api}
    ports:
      - "8080:8080"
    networks:
      - dashboard-network
    depends_on:
      postgres:
        condition: service_healthy

networks:
  dashboard-network:
    driver: bridge

volumes:
  postgres-data: